spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/bootex
spring.datasource.username=bootuser
spring.datasource.password=hjh75327!@

spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.format_sql=true
spring.jpa.show-sql=true

# S3
cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.s3.bucket=${AWS_S3_BUCKET}
cloud.aws.stack.auto=false
spring.environment=local
spring.file-dir=/src/main/resources/static/files